apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: startupscan
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret-key>
  POSTGRES_USER: <base64-encoded-user>
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_DB: <base64-encoded-db-name>