apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: startupscan
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "*"
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  AI_MODELS_DIR: "/app/ai_models"
  DATA_DIR: "/app/data"