"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-crkp-(b387n6l!ucz8)!-p0f^faj5hw9p%9n-%vgrf1lw4m&l3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'startupscan_api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

# Use dj_database_url to parse the DATABASE_URL into Django's DATABASES configuration
DB_USERNAME = os.getenv('POSTGRES_USER', 'vultradmin')
DB_PASSWORD = os.getenv('POSTGRES_PASSWORD', 'AVNS_Q5RnhlsUE9GN63FjbAc')
DB_DATABASE = os.getenv('POSTGRES_DB', 'temp_database')
DB_HOST = os.getenv('POSTGRES_HOST', 'vultr-prod-6417c5e2-c5ac-4dd5-bb0e-c2dfed3c4c54-vultr-prod-7668.vultrdb.com')
DB_PORT = os.getenv('POSTGRES_PORT', '16751')
DB_IS_AVAILABLE = all([
    DB_USERNAME, 
    DB_PASSWORD, 
    DB_DATABASE, 
    DB_HOST, 
    DB_PORT
])

DB_IGNORE_SSL= os.getenv('DB_IGNORE_SSL') == "true"


if DB_IS_AVAILABLE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_DATABASE,
            'USER': DB_USERNAME,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
    if not DB_IGNORE_SSL:
        DATABASES['default']['OPTIONS'] = {
            'sslmode': 'require',
        }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# Configurações de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS (para desenvolvimento)
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Ou para URLs:
DATASET_URLS = {
    'pitches': 'https://your-storage/pitches.csv',
    'financials': 'https://your-storage/financials.csv'
}


# settings.py
import os


# Ou URLs para datasets remotos:
# DATASET_URLS = {
#     'pitches': 'https://example.com/data/pitches.csv',
#     'financials': 'https://example.com/data/financials.csv'
# }


# Configurações para o Docker
MEDIA_ROOT = '/app/media'
MEDIA_URL = '/media/'
LOGIN_URL = 'login'
#LOGOUT_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = 'dashboard'
LOGIN_REDIRECT_URL = 'dashboard' 

#STATIC_ROOT = '/app/staticfiles'
#STATIC_URL = '/static/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AI_MODELS_DIR = os.environ.get('AI_MODELS_DIR', os.path.join(BASE_DIR, 'ai_models'))
DATA_DIR = os.environ.get('DATA_DIR', os.path.join(BASE_DIR, 'data'))

# Certifique-se que os diretórios existem
os.makedirs(AI_MODELS_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)


CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'