"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import importlib.util

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent.parent / ".env")
except Exception:
    pass

try:
    import dj_database_url
except Exception:  # pragma: no cover - fallback quando pacote não está disponível
    dj_database_url = None

from startupscan_api.i18n import SUPPORTED_UI_LANGUAGES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name: str, default: list[str] | None = None) -> list[str]:
    raw = str(os.getenv(name, "") or "").strip()
    items = [part.strip() for part in raw.split(",") if part.strip()]
    if items:
        return items
    return list(default or [])


# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.getenv("SECRET_KEY")
if not _secret_key:
    if _env_bool("DJANGO_DEBUG", False):
        _secret_key = "django-insecure-dev-only-do-not-use-in-production"
    else:
        raise RuntimeError("SECRET_KEY environment variable must be set in production.")
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["127.0.0.1", "localhost", "testserver", ".trycloudflare.com", ".onrender.com"],
)
CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ["https://*.trycloudflare.com", "https://*.onrender.com"],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'startupscan_api',
    'subscriptions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'startupscan_api.middleware.UiLanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

if importlib.util.find_spec("whitenoise") is not None:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'startupscan_api.context_processors.user_role_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# # PostgreSQL configuration (disabled — using SQLite)
# DB_USERNAME = os.getenv('POSTGRES_USER', '')
# DB_PASSWORD = os.getenv('POSTGRES_PASSWORD', '')
# DB_DATABASE = os.getenv('POSTGRES_DB', '')
# DB_HOST = os.getenv('POSTGRES_HOST', '')
# DB_PORT = os.getenv('POSTGRES_PORT', '')
# DB_IS_AVAILABLE = all([
#     DB_USERNAME,
#     DB_PASSWORD,
#     DB_DATABASE,
#     DB_HOST,
#     DB_PORT
# ])
#
# DB_IGNORE_SSL = _env_bool('DB_IGNORE_SSL', False)
#
# database_url = str(os.getenv("DATABASE_URL", "") or "").strip()
# if database_url and dj_database_url is not None:
#     DATABASES = {
#         'default': dj_database_url.parse(
#             database_url,
#             conn_max_age=600,
#             ssl_require=not DB_IGNORE_SSL,
#         )
#     }
# elif DB_IS_AVAILABLE:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': DB_DATABASE,
#             'USER': DB_USERNAME,
#             'PASSWORD': DB_PASSWORD,
#             'HOST': DB_HOST,
#             'PORT': DB_PORT,
#         }
#     }
#     if not DB_IGNORE_SSL:
#         DATABASES['default']['OPTIONS'] = {
#             'sslmode': 'require',
#         }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt'
LANGUAGES = tuple(SUPPORTED_UI_LANGUAGES)
LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# Configurações de mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS — em produção define CORS_ALLOWED_ORIGINS no .env (lista separada por vírgula)
_cors_origins = _env_list("CORS_ALLOWED_ORIGINS", [])
if _cors_origins:
    CORS_ALLOWED_ORIGINS = _cors_origins
else:
    # Só permite all-origins se DEBUG estiver activo
    CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Ou para URLs:
DATASET_URLS = {
    'pitches': 'https://your-storage/pitches.csv',
    'financials': 'https://your-storage/financials.csv'
}


# settings.py
import os


# Ou URLs para datasets remotos:
# DATASET_URLS = {
#     'pitches': 'https://example.com/data/pitches.csv',
#     'financials': 'https://example.com/data/financials.csv'
# }


MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))
MEDIA_URL = '/media/'
LOGIN_URL = 'login'
#LOGOUT_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = 'login'
LOGIN_REDIRECT_URL = 'role_home' 

#STATIC_ROOT = '/app/staticfiles'
#STATIC_URL = '/static/'

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AI_MODELS_DIR = os.environ.get('AI_MODELS_DIR', os.path.join(BASE_DIR, 'ai_models'))
DATA_DIR = os.environ.get('DATA_DIR', os.path.join(BASE_DIR, 'data'))

# Certifique-se que os diretórios existem
os.makedirs(AI_MODELS_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)


CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'

# Stripe
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PAYMENT_LINK_BASIC = os.getenv('STRIPE_PAYMENT_LINK_BASIC', '')
STRIPE_PAYMENT_LINK_PRO = os.getenv('STRIPE_PAYMENT_LINK_PRO', '')

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'noreply@startupscan.io')

# URL base do site (para links nos emails)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')