from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    BatchAnalysisResultsView,
    BatchAnalysisStatusView,
    ConnectionsHubView,
    ConnectionInterestUpdateView,
    DashboardView,
    IdeaPitchDetailView,
    IdeaPitchPDFView,
    InvestorDashboardView,
    InvestorInterestCreateView,
    IdeaPitchBuilderView,
    ModelTrainingProgressView,
    ModelManagementView,
    RoleBasedLoginView,
    RoleHomeView,
    PitchFormView,
    PitchExplainerVideoGenerateView,
    PitchPresenterGenderDetectView,
    PitchExplainerVideoProgressView,
    PitchInvestorPDFView,
    PitchReportPDFView,
    PitchResultsView,
    PublicIdeaDetailView,
    PublicIdeaFeedbackView,
    PublicIdeasView,
    StartupPitchAnalyzer,
    BatchAnalysisView,
    ModelRetrainView,
    TrainingStatusView,
    set_ui_language,
    register_view
)

urlpatterns = [
    path('analyze/', StartupPitchAnalyzer.as_view(), name='pitch-analyzer'),
    path('model/retrain/', ModelRetrainView.as_view(), name='model-retrain'),
    path('training/status/<str:task_id>/', TrainingStatusView.as_view(), name='training-status'),
    path('batch/analyze/', BatchAnalysisView.as_view(), name='batch-analyze'),
    path('batch/status/<uuid:batch_id>/', BatchAnalysisStatusView.as_view(), name='batch-status'),
    path('batch/results/<uuid:batch_id>/', BatchAnalysisResultsView.as_view(), name='batch-results'),
    path('models/', ModelManagementView.as_view(), name='model_management'),
    path('models/training/progress/<str:job_id>/', ModelTrainingProgressView.as_view(), name='model_training_progress'),
    path('investors/', InvestorDashboardView.as_view(), name='investor_dashboard'),
    path('investors/interest/<int:analysis_id>/', InvestorInterestCreateView.as_view(), name='investor_interest_create'),
    path('connections/', ConnectionsHubView.as_view(), name='connections_hub'),
    path('connections/<int:interest_id>/update/', ConnectionInterestUpdateView.as_view(), name='connection_interest_update'),
    path('home/', RoleHomeView.as_view(), name='role_home'),

    path('', DashboardView.as_view(), name='dashboard'),
    path('pitch/builder/', IdeaPitchBuilderView.as_view(), name='idea_pitch_builder'),
    path('pitch/builder/<int:submission_id>/', IdeaPitchDetailView.as_view(), name='idea_pitch_detail'),
    path('pitch/builder/<int:submission_id>/pdf/', IdeaPitchPDFView.as_view(), name='idea_pitch_pdf'),
    path('ideas/', PublicIdeasView.as_view(), name='public_ideas'),
    path('ideas/<int:submission_id>/', PublicIdeaDetailView.as_view(), name='public_idea_detail'),
    path('ideas/<int:submission_id>/feedback/', PublicIdeaFeedbackView.as_view(), name='public_idea_feedback'),
    path('analyze/form/', PitchFormView.as_view(), name='pitch_form'),
    path('results/<int:analysis_id>/', PitchResultsView.as_view(), name='pitch_results'),
    path('results/<int:analysis_id>/pdf/', PitchReportPDFView.as_view(), name='pitch_report_pdf'),
    path('results/<int:analysis_id>/pitch/pdf/', PitchInvestorPDFView.as_view(), name='pitch_investor_pdf'),
    path('results/<int:analysis_id>/video/generate/', PitchExplainerVideoGenerateView.as_view(), name='pitch_explainer_video_generate'),
    path('results/<int:analysis_id>/video/detect-gender/', PitchPresenterGenderDetectView.as_view(), name='pitch_presenter_gender_detect'),
    path('results/<int:analysis_id>/video/progress/<str:job_id>/', PitchExplainerVideoProgressView.as_view(), name='pitch_explainer_video_progress'),
    path('login/', RoleBasedLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('register/', register_view, name='register'),
    path('set-language/', set_ui_language, name='set_ui_language'),
]