# Generated by Django 6.0.4 on 2026-09-09 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('analysis_created', 'Analysis created'), ('batch_analysis', 'Batch analysis run'), ('report_viewed', 'Report viewed'), ('report_downloaded', 'Report downloaded (PDF)'), ('pitch_pdf_generated', 'Investor pitch PDF generated'), ('video_generated', 'Explainer video generated'), ('idea_created', 'Idea pitch created'), ('idea_pdf_generated', 'Idea pitch PDF generated'), ('investor_interest_sent', 'Investor interest sent')], db_index=True, max_length=40, verbose_name='Action')),
                ('target_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Target')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='When')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='superadmin__action_e3fd7f_idx')],
            },
        ),
    ]
