import json
import logging
import os

import numpy as np

from startupscan_api.modeling import _ensure_unique_report_language
from startupscan_api.services.ai_engines.prompts import build_pitch_analysis_prompts

logger = logging.getLogger(__name__)


def analyze_with_deepseek(text, financial_data, metadata, language: str = "en"):
    """
    Uses the DeepSeek API (OpenAI-compatible) to generate score + report.
    Returns (score, report, engine_used).
    """
    api_key = os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        return None, {"status": "fallback", "summary": "DEEPSEEK_API_KEY missing"}, "local-fallback"

    try:
        from openai import OpenAI

        model_name = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")
        base_url = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
        client = OpenAI(api_key=api_key, base_url=base_url)
        system_prompt, user_prompt, startup_name, uniqueness_key = build_pitch_analysis_prompts(
            text, financial_data, metadata, language,
        )

        response = client.chat.completions.create(
            model=model_name,
            temperature=0.65,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        )
        content = response.choices[0].message.content
        data = json.loads(content)

        score = float(data.get("score", 5.0))
        score = float(np.clip(score, 0.0, 10.0))
        report = {
            "status": "deepseek",
            "summary": data.get("summary", "Report generated by the advanced engine."),
            "strengths": data.get("strengths", []),
            "weaknesses": data.get("weaknesses", []),
            "recommendations": data.get("recommendations", []),
            "category_scores": data.get("category_scores", {}),
            "investor_pitch": data.get("investor_pitch", {}),
            "market_opportunity": data.get("market_opportunity", ""),
            "competitive_position": data.get("competitive_position", ""),
        }
        report = _ensure_unique_report_language(report, startup_name, uniqueness_key, language)
        return score, report, "deepseek"
    except Exception as exc:
        logger.warning("DeepSeek analysis failed, fallback to local model: %s", str(exc), exc_info=True)
        return None, {"status": "fallback", "summary": str(exc)}, "local-fallback"
