import json
import logging
import os

import numpy as np
import requests

from startupscan_api.engines import AnalysisEngine
from startupscan_api.modeling import _ensure_unique_report_language
from startupscan_api.services.ai_engines.prompts import build_pitch_analysis_prompts

logger = logging.getLogger(__name__)


def analyze_with_ollama(text, financial_data, metadata, language: str = "en"):
    """
    Uses a local Ollama instance (self-hosted, run via the `ollama` Docker
    service) to generate score + report. Returns (score, report, engine_used).

    Never attempts to pull a missing model on demand — that can take minutes
    and would block the request. If the model isn't already available on the
    Ollama host, this simply falls back to the local model like any other
    engine failure.
    """
    base_url = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434")
    model_name = os.getenv("OLLAMA_MODEL", "llama3.1:8b")
    timeout = float(os.getenv("OLLAMA_REQUEST_TIMEOUT", "120"))

    try:
        system_prompt, user_prompt, startup_name, uniqueness_key = build_pitch_analysis_prompts(
            text, financial_data, metadata, language, engine=AnalysisEngine.OLLAMA,
        )

        response = requests.post(
            f"{base_url.rstrip('/')}/api/chat",
            json={
                "model": model_name,
                "stream": False,
                "format": "json",
                "options": {"temperature": 0.65},
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
            },
            timeout=timeout,
        )
        response.raise_for_status()
        content = (response.json().get("message") or {}).get("content", "")
        data = json.loads(content)

        score = float(data.get("score", 5.0))
        score = float(np.clip(score, 0.0, 10.0))
        report = {
            "status": "ollama",
            "summary": data.get("summary", "Report generated by the balanced engine."),
            "strengths": data.get("strengths", []),
            "weaknesses": data.get("weaknesses", []),
            "recommendations": data.get("recommendations", []),
            "category_scores": data.get("category_scores", {}),
            "investor_pitch": data.get("investor_pitch", {}),
            "market_opportunity": data.get("market_opportunity", ""),
            "competitive_position": data.get("competitive_position", ""),
        }
        report = _ensure_unique_report_language(report, startup_name, uniqueness_key, language)
        return score, report, "ollama"
    except Exception as exc:
        logger.warning("Ollama analysis failed, fallback to local model: %s", str(exc), exc_info=True)
        return None, {"status": "fallback", "summary": str(exc)}, "local-fallback"
