# Generated by Django 6.0.4 on 2026-04-22 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('tier', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=20, verbose_name='Tier')),
                ('interval', models.CharField(choices=[('month', 'Mensal'), ('year', 'Anual'), ('once', 'Único (Trial)')], default='month', max_length=10, verbose_name='Intervalo')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('trial_days', models.IntegerField(default=7, help_text='Apenas relevante para planos Trial', verbose_name='Dias de trial')),
                ('stripe_product_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Product ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID')),
                ('analyses_per_month', models.IntegerField(default=3, help_text='0 = ilimitado', verbose_name='Análises/mês')),
                ('videos_per_month', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Vídeos IA/mês')),
                ('investor_interests_per_month', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Interesses de investidor/mês')),
                ('batch_max_rows', models.IntegerField(default=0, help_text='0 = ilimitado', verbose_name='Máx. linhas por batch')),
                ('gpt_analysis', models.BooleanField(default=False, verbose_name='Análise via GPT')),
                ('audio_upload', models.BooleanField(default=False, verbose_name='Upload de áudio')),
                ('video_upload', models.BooleanField(default=False, verbose_name='Upload de vídeo')),
                ('youtube_url', models.BooleanField(default=False, verbose_name='URL YouTube')),
                ('financial_data', models.BooleanField(default=False, verbose_name='Dados financeiros')),
                ('pdf_report', models.BooleanField(default=False, verbose_name='PDF relatório de análise')),
                ('pdf_investor', models.BooleanField(default=False, verbose_name='PDF pitch para investidor')),
                ('pitch_template_choice', models.BooleanField(default=False, verbose_name='Escolha de template de pitch')),
                ('pitch_gpt', models.BooleanField(default=False, verbose_name='Gerar pitch via GPT')),
                ('pitch_pdf', models.BooleanField(default=False, verbose_name='Exportar pitch PDF')),
                ('batch_analysis', models.BooleanField(default=False, verbose_name='Análise em lote (CSV)')),
                ('investor_dashboard', models.BooleanField(default=False, verbose_name='Dashboard de investidores')),
                ('video_generation', models.BooleanField(default=False, verbose_name='Gerar vídeo explicativo IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Subscrição',
                'verbose_name_plural': 'Planos de Subscrição',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Em trial'), ('active', 'Ativa'), ('past_due', 'Pagamento em atraso'), ('canceled', 'Cancelada'), ('incomplete', 'Incompleta'), ('inactive', 'Inativa')], default='trialing', max_length=20, verbose_name='Status')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Subscription ID')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do trial')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do período')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar no fim do período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Subscrição',
                'verbose_name_plural': 'Subscrições',
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('analyses_count', models.IntegerField(default=0, verbose_name='Análises realizadas')),
                ('videos_count', models.IntegerField(default=0, verbose_name='Vídeos gerados')),
                ('investor_interests_count', models.IntegerField(default=0, verbose_name='Interesses enviados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Uso Mensal',
                'verbose_name_plural': 'Usos Mensais',
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
