# Generated by Django 6.0.4 on 2026-09-03 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_multicurrency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyusage',
            options={'verbose_name': 'Monthly Usage', 'verbose_name_plural': 'Monthly Usages'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price_usd'], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='analyses_count',
            field=models.IntegerField(default=0, verbose_name='Analyses performed'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='investor_interests_count',
            field=models.IntegerField(default=0, verbose_name='Interests sent'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='month',
            field=models.IntegerField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='videos_count',
            field=models.IntegerField(default=0, verbose_name='Videos generated'),
        ),
        migrations.AlterField(
            model_name='monthlyusage',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='Cancel at period end'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Period end'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Period start'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('inactive', 'Inactive')], default='trialing', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial end'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='analyses_per_month',
            field=models.IntegerField(default=3, help_text='0 = unlimited', verbose_name='Analyses/month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='audio_upload',
            field=models.BooleanField(default=False, verbose_name='Audio upload'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='batch_analysis',
            field=models.BooleanField(default=False, verbose_name='Batch analysis (CSV)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='batch_max_rows',
            field=models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='Max rows per batch'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='financial_data',
            field=models.BooleanField(default=False, verbose_name='Financial data'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='gpt_analysis',
            field=models.BooleanField(default=False, verbose_name='GPT analysis'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('once', 'One-time (Trial)')], default='month', max_length=10, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='investor_dashboard',
            field=models.BooleanField(default=False, verbose_name='Investor dashboard'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='investor_interests_per_month',
            field=models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='Investor interests/month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pdf_investor',
            field=models.BooleanField(default=False, verbose_name='Investor pitch PDF'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pdf_report',
            field=models.BooleanField(default=False, verbose_name='Analysis report PDF'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pitch_gpt',
            field=models.BooleanField(default=False, verbose_name='Generate pitch via GPT'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pitch_pdf',
            field=models.BooleanField(default=False, verbose_name='Export pitch PDF'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='pitch_template_choice',
            field=models.BooleanField(default=False, verbose_name='Pitch template choice'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_aoa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Price (AOA)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price (EUR)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=7, help_text='Only relevant for Trial plans', verbose_name='Trial days'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='video_generation',
            field=models.BooleanField(default=False, verbose_name='Generate AI explainer video'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='video_upload',
            field=models.BooleanField(default=False, verbose_name='Video upload'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='videos_per_month',
            field=models.IntegerField(default=0, help_text='0 = unlimited', verbose_name='AI videos/month'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='youtube_url',
            field=models.BooleanField(default=False, verbose_name='YouTube URL'),
        ),
    ]
