# Generated by Django 6.0.4 on 2026-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_translate_labels_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='business_model_canvas',
            field=models.BooleanField(default=False, verbose_name='Business Model Canvas in report'),
        ),
    ]
