# Generated by Django 6.0.4 on 2026-09-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_add_business_model_canvas_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='deepseek_analysis',
            field=models.BooleanField(default=False, verbose_name='Advanced engine analysis'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='local_analysis',
            field=models.BooleanField(default=True, verbose_name='Fast (local) engine analysis'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ollama_analysis',
            field=models.BooleanField(default=False, verbose_name='Balanced engine analysis'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='gpt_analysis',
            field=models.BooleanField(default=False, verbose_name='Elite engine analysis'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=20, verbose_name='Tier'),
        ),
    ]
