# Generated by Django 5.0.2 on 2025-05-22 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pitchanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Análise de Pitch', 'verbose_name_plural': 'Análises de Pitch'},
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Taxa de Queima (R$/mês)'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confiança da Análise (%)'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de contato'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='industry',
            field=models.CharField(choices=[('tech', 'Tecnologia'), ('health', 'Saúde'), ('finance', 'Finanças'), ('education', 'Educação'), ('ecommerce', 'E-commerce'), ('other', 'Outro')], default='tech', max_length=20, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versão do Modelo'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo de processamento (segundos)'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='startup_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Startup'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completo'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de submissão'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='pitchanalysis',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/audio/%Y/%m/%d/', verbose_name='Arquivo de Áudio'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(1000)], verbose_name='Taxa de Crescimento (%)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Metadados Técnicos'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Margem de Lucro (%)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='report',
            field=models.JSONField(default=dict, verbose_name='Relatório Completo'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Receita Anual (R$)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='success_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Score de Sucesso'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='text',
            field=models.TextField(verbose_name='Texto do Pitch'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/video/%Y/%m/%d/', verbose_name='Arquivo de Vídeo'),
        ),
        migrations.AddIndex(
            model_name='pitchanalysis',
            index=models.Index(fields=['created_at'], name='startupscan_created_8b94a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchanalysis',
            index=models.Index(fields=['status'], name='startupscan_status_195e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchanalysis',
            index=models.Index(fields=['success_score'], name='startupscan_success_f06ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchanalysis',
            index=models.Index(fields=['industry'], name='startupscan_industr_b2f9eb_idx'),
        ),
    ]
