# Generated by Django 6.0.3 on 2026-03-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0002_alter_pitchanalysis_options_pitchanalysis_burn_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaPitchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup_name', models.CharField(max_length=120, verbose_name='Nome da startup')),
                ('one_liner', models.CharField(blank=True, default='', max_length=300)),
                ('problem', models.TextField(verbose_name='Problema')),
                ('solution', models.TextField(verbose_name='Solução')),
                ('target_customer', models.TextField(verbose_name='Cliente-alvo')),
                ('market_size', models.TextField(blank=True, default='')),
                ('business_model', models.TextField(verbose_name='Modelo de negócio')),
                ('competitive_advantage', models.TextField(blank=True, default='')),
                ('traction', models.TextField(blank=True, default='')),
                ('team', models.TextField(blank=True, default='')),
                ('funding_goal', models.TextField(blank=True, default='')),
                ('use_of_funds', models.TextField(blank=True, default='')),
                ('call_to_action', models.TextField(blank=True, default='')),
                ('model_source', models.CharField(choices=[('local', 'Local'), ('gpt', 'GPT')], default='local', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('generated', 'Pitch gerado')], default='draft', max_length=20)),
                ('generated_pitch', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Submissão de Ideia para Pitch',
                'verbose_name_plural': 'Submissões de Ideia para Pitch',
                'ordering': ['-created_at'],
            },
        ),
    ]
