# Generated by Django 6.0.3 on 2026-03-23 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0003_alter_pitchanalysis_burn_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchanalysis',
            name='burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Taxa de Queima (AOA/mês)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Receita Anual (AOA)'),
        ),
    ]
