# Generated by Django 6.0.3 on 2026-03-23 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0010_investorconnectioninterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaPublicFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Estrelas (1 a 5)')),
                ('endorsed', models.BooleanField(default=False, verbose_name='Apoia esta ideia')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comentário público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_feedbacks', to='startupscan_api.ideapitchsubmission', verbose_name='Ideia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_public_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Feedback Público de Ideia',
                'verbose_name_plural': 'Feedbacks Públicos de Ideias',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['stars'], name='startupscan_stars_1b66eb_idx'), models.Index(fields=['endorsed'], name='startupscan_endorse_0571fd_idx'), models.Index(fields=['created_at'], name='startupscan_created_269c9c_idx'), models.Index(fields=['updated_at'], name='startupscan_updated_f13752_idx')],
                'constraints': [models.UniqueConstraint(fields=('submission', 'user'), name='unique_public_feedback_per_user_submission')],
            },
        ),
    ]
