# Generated by Django 6.0.4 on 2026-09-03 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

OLD_TO_NEW_ROLE = {
    'empreendedor': 'entrepreneur',
    'investidor': 'investor',
    'publico_geral': 'general_public',
    'analista': 'analyst',
}


def forwards_translate_roles(apps, schema_editor):
    UserProfile = apps.get_model('startupscan_api', 'UserProfile')
    for old_value, new_value in OLD_TO_NEW_ROLE.items():
        UserProfile.objects.filter(role=old_value).update(role=new_value)


def backwards_translate_roles(apps, schema_editor):
    UserProfile = apps.get_model('startupscan_api', 'UserProfile')
    for old_value, new_value in OLD_TO_NEW_ROLE.items():
        UserProfile.objects.filter(role=new_value).update(role=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0011_ideapublicfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investor'), ('general_public', 'General public'), ('analyst', 'Analyst'), ('admin', 'Administrator')], default='general_public', max_length=30, verbose_name='Access profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RunPython(forwards_translate_roles, backwards_translate_roles),
    ]
