# Generated by Django 6.0.3 on 2026-03-25 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0011_ideapublicfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20, verbose_name='Plano')),
                ('interval', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Periodicidade')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Ativa'), ('past_due', 'Em atraso'), ('canceled', 'Cancelada'), ('incomplete', 'Incompleta'), ('expired', 'Expirada'), ('unpaid', 'Não paga'), ('paused', 'Pausada')], default='incomplete', max_length=20, verbose_name='Status')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Stripe Subscription ID')),
                ('trial_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Início do trial')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim do trial')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='Início do período atual')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim do período atual')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar no fim do período')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Subscrição de Utilizador',
                'verbose_name_plural': 'Subscrições de Utilizador',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Valor (cêntimos)')),
                ('currency', models.CharField(default='usd', max_length=10, verbose_name='Moeda')),
                ('status', models.CharField(default='pending', max_length=30, verbose_name='Status de pagamento')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Stripe Invoice ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Stripe Payment Intent ID')),
                ('invoice_pdf_url', models.URLField(blank=True, default='', verbose_name='URL da fatura')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='startupscan_api.usersubscription', verbose_name='Subscrição')),
            ],
            options={
                'verbose_name': 'Transação de Pagamento',
                'verbose_name_plural': 'Transações de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='startupscan_status_2d989f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan', 'interval'], name='startupscan_plan_1ef221_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['current_period_end'], name='startupscan_current_695cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['trial_ends_at'], name='startupscan_trial_e_701863_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='startupscan_status_80bd32_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='startupscan_created_48ccf1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paid_at'], name='startupscan_paid_at_fd1a98_idx'),
        ),
    ]
