# Generated by Django 6.0.3 on 2026-03-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0012_usersubscription_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideapitchsubmission',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Visível na área pública'),
        ),
    ]
