# Generated by Django 6.0.4 on 2026-09-03 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0012_rename_role_values_to_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideapitchsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Idea Pitch Submission', 'verbose_name_plural': 'Idea Pitch Submissions'},
        ),
        migrations.AlterModelOptions(
            name='ideapublicfeedback',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Idea Public Feedback', 'verbose_name_plural': 'Idea Public Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='investorconnectioninterest',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Connection Interest', 'verbose_name_plural': 'Connection Interests'},
        ),
        migrations.AlterModelOptions(
            name='pitchanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pitch Analysis', 'verbose_name_plural': 'Pitch Analyses'},
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='business_model',
            field=models.TextField(verbose_name='Business model'),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='problem',
            field=models.TextField(verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='solution',
            field=models.TextField(verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='startup_name',
            field=models.CharField(max_length=120, verbose_name='Startup name'),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Pitch generated')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='target_customer',
            field=models.TextField(verbose_name='Target customer'),
        ),
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ideapublicfeedback',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Public comment'),
        ),
        migrations.AlterField(
            model_name='ideapublicfeedback',
            name='endorsed',
            field=models.BooleanField(default=False, verbose_name='Endorses this idea'),
        ),
        migrations.AlterField(
            model_name='ideapublicfeedback',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stars (1 to 5)'),
        ),
        migrations.AlterField(
            model_name='ideapublicfeedback',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_feedbacks', to='startupscan_api.ideapitchsubmission', verbose_name='Idea'),
        ),
        migrations.AlterField(
            model_name='ideapublicfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_public_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_interests', to='startupscan_api.pitchanalysis', verbose_name='Analysis of interest'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='entrepreneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_connection_interests', to=settings.AUTH_USER_MODEL, verbose_name='Entrepreneur'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='entrepreneur_reply',
            field=models.TextField(blank=True, default='', verbose_name='Entrepreneur reply'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_interests', to=settings.AUTH_USER_MODEL, verbose_name='Investor'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='investor_message',
            field=models.TextField(blank=True, default='', verbose_name='Investor message'),
        ),
        migrations.AlterField(
            model_name='investorconnectioninterest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('connected', 'Connected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20, verbose_name='Connection status'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/audio/%Y/%m/%d/', verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Burn Rate (AOA/month)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Analysis Confidence (%)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/docs/%Y/%m/%d/', verbose_name='Submitted File'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='explainer_video_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/explainer/%Y/%m/%d/', verbose_name='AI Explainer Video'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='growth_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(1000)], verbose_name='Growth Rate (%)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='industry',
            field=models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('finance', 'Finance'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('other', 'Other')], default='tech', max_length=20, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Technical Metadata'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Model Version'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='presenter_face_image_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/presenter/%Y/%m/%d/', verbose_name='Presenter Face'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing time (seconds)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Profit Margin (%)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='report',
            field=models.JSONField(default=dict, verbose_name='Full Report'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Revenue (AOA)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='startup_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Startup Name'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='success_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Success Score'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='text',
            field=models.TextField(verbose_name='Pitch Text'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='pitches/video/%Y/%m/%d/', verbose_name='Video File'),
        ),
    ]
