# Generated by Django 6.0.3 on 2026-03-26 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0013_ideapitchsubmission_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código do plano')),
                ('name', models.CharField(max_length=80, verbose_name='Nome do plano')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Stripe Product ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Subscrição',
                'verbose_name_plural': 'Planos de Subscrição',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='startupscan_code_c6f2b9_idx'), models.Index(fields=['is_active'], name='startupscan_is_acti_f6ec14_idx'), models.Index(fields=['display_order'], name='startupscan_display_15e707_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], max_length=20, verbose_name='Periodicidade')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Valor (cêntimos)')),
                ('currency', models.CharField(default='usd', max_length=10, verbose_name='Moeda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Stripe Price ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='startupscan_api.subscriptionplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Preço de Plano de Subscrição',
                'verbose_name_plural': 'Preços de Planos de Subscrição',
                'indexes': [models.Index(fields=['interval'], name='startupscan_interva_7460de_idx'), models.Index(fields=['is_active'], name='startupscan_is_acti_87c685_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'interval'), name='unique_plan_interval_price')],
            },
        ),
    ]
