# Generated by Django 6.0.4 on 2026-09-09 16:23

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def convert_existing_amounts_to_eur(apps, schema_editor):
    """
    Historical PitchAnalysis.revenue/burn_rate values were entered assuming
    Angolan Kwanza (AOA) -- the model's old verbose_name said so explicitly.
    Now that EUR is the platform's canonical storage currency, do a one-time
    conversion of every existing row using the current AOA/EUR rate so old
    and new analyses stay on a consistent footing (see
    startupscan_api/utils/currency.py for the live-rate source and fallback).
    """
    from startupscan_api.utils.currency import get_exchange_rates

    PitchAnalysis = apps.get_model('startupscan_api', 'PitchAnalysis')
    rates = get_exchange_rates()
    aoa_per_eur = Decimal(str(rates.get('AOA') or 1107.6))  # matches currency.py's static fallback

    for analysis in PitchAnalysis.objects.exclude(revenue__isnull=True).only('id', 'revenue', 'burn_rate').iterator():
        updated_fields = []
        if analysis.revenue is not None:
            analysis.revenue = analysis.revenue / aoa_per_eur
            updated_fields.append('revenue')
        if analysis.burn_rate is not None:
            analysis.burn_rate = analysis.burn_rate / aoa_per_eur
            updated_fields.append('burn_rate')
        if updated_fields:
            analysis.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    # Intentionally irreversible: reversing would need the exact historical
    # rate used at forward-migration time, which isn't recorded anywhere.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0014_translate_category_score_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchanalysis',
            name='burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Burn Rate (EUR/month)'),
        ),
        migrations.AlterField(
            model_name='pitchanalysis',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Revenue (EUR)'),
        ),
        migrations.RunPython(convert_existing_amounts_to_eur, noop_reverse),
    ]
