# Generated by Django 6.0.3 on 2026-03-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0014_subscriptionplan_subscriptionplanprice'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriptionplanprice',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_price_id', ''), _negated=True), fields=('stripe_price_id',), name='unique_stripe_price_id_non_empty'),
        ),
    ]
