# Generated by Django 6.0.4 on 2026-09-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0015_revenue_burn_rate_currency_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideapitchsubmission',
            name='model_source',
            field=models.CharField(choices=[('local', 'Local'), ('gpt', 'GPT'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama')], default='local', max_length=10),
        ),
    ]
