# Generated by Django 6.0.4 on 2026-09-10 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0016_alter_ideapitchsubmission_model_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('gpt', 'GPT'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama')], max_length=20, verbose_name='Engine')),
                ('purpose', models.CharField(choices=[('analysis_system', 'Analysis — system prompt'), ('analysis_user', 'Analysis — user prompt'), ('generation_system', 'Pitch generation — system prompt'), ('generation_user', 'Pitch generation — user prompt')], max_length=30, verbose_name='Purpose')),
                ('content', models.TextField(help_text='Uses $variable placeholders. Literal { and } (e.g. JSON examples) never need escaping.', verbose_name='Prompt content')),
                ('is_active', models.BooleanField(default=True, help_text='When off, this engine falls back to the built-in default prompt for this slot.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last updated by')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['engine', 'purpose'],
                'constraints': [models.UniqueConstraint(fields=('engine', 'purpose'), name='unique_prompt_per_engine_purpose')],
            },
        ),
    ]
