# Generated by Django 6.0.4 on 2026-09-10 06:18
"""
Seeds one PromptTemplate row per (engine, purpose) combination from the
built-in defaults in services/ai_engines/prompt_defaults.py, so a fresh
database always starts with the exact prompt text that used to be hardcoded
in modeling.py / services/pitch/generator.py.

Uses get_or_create so it's safe to run more than once and never clobbers a
row an admin has already edited.
"""
from django.db import migrations

from startupscan_api.services.ai_engines.prompt_defaults import (
    DEFAULT_PROMPTS,
    PROMPT_ENGINE_VALUES,
    PURPOSE_VALUES,
)


def seed_default_prompts(apps, schema_editor):
    PromptTemplate = apps.get_model('startupscan_api', 'PromptTemplate')
    for engine in PROMPT_ENGINE_VALUES:
        for purpose in PURPOSE_VALUES:
            PromptTemplate.objects.get_or_create(
                engine=engine,
                purpose=purpose,
                defaults={'content': DEFAULT_PROMPTS[purpose], 'is_active': True},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('startupscan_api', '0017_prompttemplate'),
    ]

    operations = [
        migrations.RunPython(seed_default_prompts, noop_reverse),
    ]
