SUBSCRIPTION_PLAN_BASIC = "basic"
SUBSCRIPTION_PLAN_PRO = "pro"
SUBSCRIPTION_PLAN_CHOICES = (SUBSCRIPTION_PLAN_BASIC, SUBSCRIPTION_PLAN_PRO)

SUBSCRIPTION_INTERVAL_MONTHLY = "monthly"
SUBSCRIPTION_INTERVAL_ANNUAL = "annual"
SUBSCRIPTION_INTERVAL_CHOICES = (
    SUBSCRIPTION_INTERVAL_MONTHLY,
    SUBSCRIPTION_INTERVAL_ANNUAL,
)

TRIAL_DAYS_FULL_ACCESS = 14
